version: 2
updates:
- package-ecosystem: gradle
  directory: "/10-bitClockWidget"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fastlane
    versions:
    - 2.178.0
