# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build and deploy the app on the Play Store production track"
  lane :deploy do
    storeFile = sh("printf $(pwd)/../keystore.jks")
    gradle(
      project_dir: "./10-bitClockWidget",
      task: "clean assembleRelease",
      properties: {
        "android.injected.signing.store.file" => "#{storeFile}",
        "android.injected.signing.store.password" => "#{ENV['STORE_PASSWORD']}",
        "android.injected.signing.key.alias" => "#{ENV['KEY_ALIAS']}",
        "android.injected.signing.key.password" => "#{ENV['KEY_PASSWORD']}",
      },
      print_command: false
    )
    upload_to_play_store
  end
end
