name: Android
on:
  push:
    branches:
      - master
    tags:
      - "**"
    paths:
      - "10-bitClockWidget/**"
      - ".github/workflows/android.yaml"
  pull_request:
    branches:
      - master
    paths:
      - "10-bitClockWidget/**"
      - ".github/workflows/android.yaml"

env:
  JDK_DISTRIBUTION: temurin
  JAVA_VERSION: 17

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - run: ./10-bitClockWidget/gradlew -p ./10-bitClockWidget assembleDebug

  deploy:
    name: Deploy
    if: github.repository == 'ashutoshgngwr/10-bitClockWidget' && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: [assemble]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags -f
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - run: >-
          echo "$SERVICE_ACCOUNT_KEY" > service-account-key.json;
          echo "$JKS_STORE" | base64 --decode > keystore.jks;
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          JKS_STORE: ${{ secrets.JKS_STORE }}
      - run: bundle install && bundle exec fastlane deploy
        env:
          STORE_PASSWORD: ${{ secrets.JKS_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.JKS_ALIAS }}
          KEY_PASSWORD: ${{ secrets.JKS_ALIAS_PASSWORD }}
      - id: get_tag_message
        run: >-
          TAG_BODY="$(git tag  --list --format='%(contents:body)' ${GITHUB_REF/'refs/tags/'/''})";
          TAG_BODY="${TAG_BODY//'%'/'%25'}";
          TAG_BODY="${TAG_BODY//$'\n'/'%0A'}";
          TAG_BODY="${TAG_BODY//$'\r'/'%0D'}";
          echo "::set-output name=message::${TAG_BODY}";
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.get_tag_message.outputs.message }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./10-bitClockWidget/app/build/outputs/apk/release/app-release.apk
          asset_name: 10-bitClockWidget-release.apk
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./10-bitClockWidget/app/build/outputs/mapping/release/mapping.txt
          asset_name: retrace-mapping.txt
          asset_content_type: text/plain
      - if: ${{ always() }}
        run: rm -f service-account-key.json keystore.jks
